export { default as NFLTeamHome } from './team-home'
export { default as NFLTeamNews } from './team-news'
export { default as NFLTeamPlayers } from './team-players'
export { default as NFLTeamSchedule } from './team-schedule'
export { default as NFLTeamStats } from './team-stats'
